Enable local execution of the application in harmony with Solr and Apache plus other improvements.
* Stack the toasts in order to save more space on the screen

* Avoid regenerating thumbnails on account of checksum being null

* Calculate and add a checksum field for every MediFile

* Allow the helper scripts be run from other locations

* Removed the build script replacing it with a command in the start script

* Renamed arcadeia service to app and called the project arcadeia instead

* Removed an unncessesary volume mount from the solr service

* Improved overriding of docker compose values

* Correctly handle null paths for ffmpeg and yt-dlp

* Support local execution and include the required files in the build package

* Fixed the solr URL for local runs

* The ffmpeg and yt-dlp paths are no longer required which results in using the system path

* Mount utilities no longer have fixed paths and are searched in the system path

* Another attempt at excluding the Site and Release folders

* Removed some more unnecessary and duplicate files

* Improved the base artifacts folder and excluded unnecessary files

* Renamed the build directory again and eliminate the root directoy in the artifcats

* Use dist directory instead of build since a build file exists

* Pre-create the build directory

* Artifacts should not be included from outside the project folder

* Pass the runtime argument correctly for each architecture

* Override the global before script in the build stage

* Build the project for different architectures and publish them as artifacts

* Cleaned up a bit

* Back to using ubuntu and removed the GPU stuff as it doesn't seem to work

* Trying the original debian distro again

* Added the drivers that enable gpu support

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,17 +1,25 @@
 #!/bin/bash
 #
-# Start the docker compose application in production mode.
+# Start the docker compose application in different supported modes or build it.
 
 set -e
+
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+pushd $SCRIPT_DIR > /dev/null 2>&1
+
+AVAILABLE_COMMANDS=$(find . -maxdepth 1 -type f -name "docker-compose-*.yml" | sed -E 's|./docker-compose-(.*)\.yml|\1|' | sort | uniq)
 
 function show_help {
   echo "Usage: $0 [COMMAND] [SERVICE] [OPTIONS]"
   echo
-  exit 0
+  echo "COMMAND:"
+  echo
+  echo "$AVAILABLE_COMMANDS" | awk '{print "  - "$1}'
 }
 
 if [[ "$1" == "--help" || "$1" == "-h" ]]; then
   show_help
+  exit 0
 fi
 
 if [ -f ".env" ]; then
@@ -25,15 +33,28 @@ fi
 if [ $# -ge 1 ]; then
   export COMMAND=$1
   shift
+else
+  export COMMAND=production
 fi
 
-SECOND_COMPOSE_FILE="docker-compose-${COMMAND:-production}.yml"
+if ! echo "$AVAILABLE_COMMANDS" | grep -qw "$COMMAND"; then
+  echo "Error: Invalid command '$COMMAND'"
+  echo
+  show_help
+  exit 1
+fi
+
+SECOND_COMPOSE_FILE="docker-compose-${COMMAND}.yml"
 if [ ! -f "$SECOND_COMPOSE_FILE" ]; then
   echo "Error: $SECOND_COMPOSE_FILE does not exist."
   exit 1
 fi
 
-if [ $COMMAND != "debug" ]; then
+if [ "$COMMAND" == "build" ]; then
+  exec docker compose -f docker-compose.yml -f "$SECOND_COMPOSE_FILE" build --pull $@
+fi
+
+if [ "$COMMAND" != "debug" ]; then
   docker compose -f docker-compose.yml -f "$SECOND_COMPOSE_FILE" pull
 
   if [ $# -eq 0 ]; then
@@ -42,3 +63,14 @@ if [ $COMMAND != "debug" ]; then
 fi
 
 docker compose -f docker-compose.yml -f "$SECOND_COMPOSE_FILE" up "$@"
+
+if [ "$COMMAND" == "local" ]; then
+  OS=$(uname -s | tr '[:upper:]' '[:lower:]')
+
+  if [[ -f "$SCRIPT_DIR/Arcadeia.dll" ]]; then
+    if [[ "$OS" == "darwin" ]]; then
+      xattr -r -d com.apple.quarantine "$SCRIPT_DIR"
+    fi
+    exec dotnet Arcadeia.dll
+  fi
+fi
